import type { WeeklySummary } from '../storage/weekly-summary.js';

export function formatSlackDigest(summary: WeeklySummary): Record<string, unknown> {
  const totalCost = summary.totalCostUsd?.toFixed(4) ?? '—';
  const avgEfficiency = summary.avgEfficiencyScore?.toFixed(1) ?? '—';
  const topAntiPatternEntry = Object.entries(summary.antiPatternCounts ?? {})
    .sort(([, a], [, b]) => b - a)[0];
  const topAntiPattern = topAntiPatternEntry ? topAntiPatternEntry[0] : 'none';

  return {
    blocks: [
      {
        type: 'header',
        text: { type: 'plain_text', text: '🤖 Weekly AI Coding Summary' },
      },
      {
        type: 'section',
        fields: [
          { type: 'mrkdwn', text: `*Total Cost:*\n$${totalCost}` },
          { type: 'mrkdwn', text: `*Avg Efficiency:*\n${avgEfficiency}/100` },
          { type: 'mrkdwn', text: `*Sessions:*\n${summary.sessionCount}` },
          { type: 'mrkdwn', text: `*Top Anti-pattern:*\n\`${topAntiPattern}\`` },
        ],
      },
      {
        type: 'divider',
      },
      {
        type: 'context',
        elements: [
          {
            type: 'mrkdwn',
            text: '_Generated by NR AI Observatory_',
          },
        ],
      },
    ],
  };
}
