import {
  EVENT_SCHEMA_VERSION,
  createLogger,
  redact,
  safeForLog,
  loadConfig,
  createAiRequest,
  createAiResponse,
  createAiMessage,
  createAiAgentTaskSummary,
  createAiAntiPattern,
  createAiAgentMessage,
  createAiContextReset,
  aiRequestToNrEvent,
  aiResponseToNrEvent,
  aiMessageToNrEvent,
  aiAgentTaskSummaryToNrEvent,
  aiAntiPatternToNrEvent,
  aiAgentMessageToNrEvent,
  aiContextResetToNrEvent,
  extractAnthropicTokens,
  extractGeminiTokens,
  extractOpenAITokens,
  extractBedrockTokens,
  extractMistralTokens,
  extractCohereTokens,
  extractStreamTokens,
  safeInt,
  TokenAccumulator,
  calculateCost,
  resolveModelPricing,
  initPricing,
  loadCustomPricing,
  PricingTable,
  DEFAULT_PRICING_TABLE,
  RequestTimer,
  sendEvents,
  sendMetrics,
  sendLogs,
  OtlpTransport,
  OtlpEventBridge,
  EventBuffer,
  MetricAggregator,
  HarvestScheduler,
  snapshotsToNrMetrics,
  AiErrorClassification,
  classifyError,
  classifyErrorDetailed,
  isRetryable,
  RETRYABLE,
  extractRateLimitHeaders,
  truncateErrorMessage,
} from './index.js';

describe('shared package', () => {
  // EVENT_SCHEMA_VERSION must be importable from the
  // package root so consumers can `import { EVENT_SCHEMA_VERSION } from
  // '@newrelic/ai-telemetry'` per the documented public API.
  it('exports EVENT_SCHEMA_VERSION from the package root', () => {
    expect(EVENT_SCHEMA_VERSION).toBe(1);
  });

  it('all top-level value exports are defined', () => {
    // Verifies that no symbol was accidentally removed from the re-export chain.
    // Type-only exports are checked by the TypeScript build.
    const symbols = [
      createLogger,
      redact,
      safeForLog,
      loadConfig,
      createAiRequest,
      createAiResponse,
      createAiMessage,
      createAiAgentTaskSummary,
      createAiAntiPattern,
      createAiAgentMessage,
      createAiContextReset,
      aiRequestToNrEvent,
      aiResponseToNrEvent,
      aiMessageToNrEvent,
      aiAgentTaskSummaryToNrEvent,
      aiAntiPatternToNrEvent,
      aiAgentMessageToNrEvent,
      aiContextResetToNrEvent,
      extractAnthropicTokens,
      extractGeminiTokens,
      extractOpenAITokens,
      extractBedrockTokens,
      extractMistralTokens,
      extractCohereTokens,
      extractStreamTokens,
      safeInt,
      TokenAccumulator,
      calculateCost,
      resolveModelPricing,
      initPricing,
      loadCustomPricing,
      PricingTable,
      DEFAULT_PRICING_TABLE,
      RequestTimer,
      sendEvents,
      sendMetrics,
      sendLogs,
      OtlpTransport,
      OtlpEventBridge,
      EventBuffer,
      MetricAggregator,
      HarvestScheduler,
      snapshotsToNrMetrics,
      AiErrorClassification,
      classifyError,
      classifyErrorDetailed,
      isRetryable,
      RETRYABLE,
      extractRateLimitHeaders,
      truncateErrorMessage,
    ];
    for (const sym of symbols) {
      expect(sym).toBeDefined();
    }
  });
});
